from __future__ import annotations

import re


METRIC_ALIASES = {
    "accuracy": "accuracy",
    "acc": "accuracy",
    "точность": "accuracy",
    "precision": "precision",
    "prec": "precision",
    "точность класса": "precision",
    "recall": "recall",
    "rec": "recall",
    "полнота": "recall",
    "f1": "f1",
    "f1-score": "f1",
    "f1 score": "f1",
    "f1_score": "f1",
    "fb1": "f1",
    "f-мера": "f1",
    "hard dice": "hard_dice",
    "hard_dice": "hard_dice",
    "dice score": "dice",
    "dice": "dice",
    "hard iou": "hard_iou",
    "hard_iou": "hard_iou",
    "intersection over union": "iou",
    "iou": "iou",
    "mean iou": "miou",
    "mean_iou": "miou",
    "miou": "miou",
    "boundary f1": "boundary_f1",
    "boundary_f1": "boundary_f1",
    "map50-95": "map50_95",
    "map50_95": "map50_95",
    "map 50-95": "map50_95",
    "map@0.50:0.95": "map50_95",
    "map50": "map50",
    "map 50": "map50",
    "map@0.50": "map50",
    "map25": "map25",
    "map 25": "map25",
    "map@0.25": "map25",
    "map75": "map75",
    "map 75": "map75",
    "map@0.75": "map75",
    "average precision": "ap",
    "ap": "ap",
    "ap50": "ap50",
    "ap 50": "ap50",
    "ap@0.50": "ap50",
    "ap75": "ap75",
    "ap 75": "ap75",
    "ap@0.75": "ap75",
    "average recall": "ar",
    "ar": "ar",
    "panoptic quality": "pq",
    "pq": "pq",
    "hausdorff95": "hausdorff95",
    "hausdorff 95": "hausdorff95",
    "assd": "assd",
    "rmse": "rmse",
    "mae": "mae",
    "mse": "mse",
    "mean squared error": "mse",
    "top-1 accuracy": "top1_accuracy",
    "top1 accuracy": "top1_accuracy",
    "top1_accuracy": "top1_accuracy",
    "top-5 accuracy": "top5_accuracy",
    "top5 accuracy": "top5_accuracy",
    "top5_accuracy": "top5_accuracy",
    "r²": "r2",
    "r2": "r2",
    "auroc": "auroc",
    "roc auc": "auroc",
    "roc_auc": "auroc",
    "auprc": "auprc",
    "pr auc": "auprc",
    "pr_auc": "auprc",
    "log loss": "log_loss",
    "log_loss": "log_loss",
    "brier score": "brier_score",
    "brier_score": "brier_score",
    "mrr": "mrr",
    "mar": "mar",
    "mndcg": "mndcg",
    "success rate": "success_rate",
    "partial rate": "partial_rate",
    "fail rate": "fail_rate",
    "correctness": "correctness",
    "answer coverage": "answer_coverage",
    "mean tool calls": "mean_tool_calls",
    "mean tokens": "mean_tokens",
    "mean wall time": "mean_wall_time_seconds",
    "avg latency": "avg_latency_seconds",
    "avg latency (s)": "avg_latency_seconds",
    "mean latency": "avg_latency_seconds",
    "mean latency (ms)": "avg_latency_seconds",
    "p95 latency": "p95_latency_seconds",
    "p95 latency (s)": "p95_latency_seconds",
    "latency score": "latency_score_seconds",
    "latency_score": "latency_score_seconds",
    "peak rss": "peak_rss_mb",
    "memory": "memory_mb",
    "memory usage": "memory_mb",
    "memory baseline": "memory_mb",
    "throughput": "throughput_ops_per_second",
    "throughput (ops/s)": "throughput_ops_per_second",
    "feature count": "feature_count",
    "test count": "test_count",
    "artifact size": "artifact_size_mb",
    "separability delta": "separability_delta",
    "ndcg": "ndcg",
    "u_ndcg": "u_ndcg",
    "u recall": "u_recall",
    "u_recall": "u_recall",
    "swebench": "swebench",
    "swe bench": "swebench",
    "swe-bench": "swebench",
    "runtime": "runtime_seconds",
    "runtime seconds": "runtime_seconds",
    "processing time": "runtime_seconds",
    "sign time": "sign_time_seconds",
    "verify time": "verify_time_seconds",
    "sync time (w/o cache)": "sync_time_without_cache_seconds",
    "sync time (w/ cache)": "sync_time_with_cache_seconds",
    "speedup": "speedup",
    "score": "score",
    "auc": "auroc",
    "au-roc": "auroc",
    "specificity": "specificity",
    "pro": "pro",
    "bleu": "bleu",
    "bleu-2": "bleu_2",
    "bleu 2": "bleu_2",
    "bleu-1": "bleu_1",
    "bleu 1": "bleu_1",
    "bleu-3": "bleu_3",
    "bleu 3": "bleu_3",
    "bleu-4": "bleu_4",
    "bleu 4": "bleu_4",
    "rouge-l": "rouge_l",
    "rougel": "rouge_l",
    "rougel-1": "rouge_l_1",
    "rougel 1": "rouge_l_1",
    "rougel-2": "rouge_l_2",
    "rougel 2": "rouge_l_2",
    "meteor": "meteor",
    "cider": "cider",
    "text2mol": "text2mol",
    "mfu": "mfu",
    "tflop/s/gpu": "tflops_per_second_gpu",
    "tflops/gpu": "tflops_per_second_gpu",
    "tokens/s/gpu": "tokens_per_second_gpu",
    "tok/s/gpu": "tokens_per_second_gpu",
    "requests/sec": "requests_per_second",
    "req/sec": "requests_per_second",
    "wasm size": "artifact_size_kb",
    "response stdev": "latency_stdev_seconds",
    "mean response time": "avg_latency_seconds",
    "max latency": "max_latency_seconds",
    "fragmented memory": "memory_mb",
    "hbm": "memory_mb",
    "hbm/gpu": "memory_mb",
    "fragmentation": "fragmentation_ratio",
    "assertion count": "assertion_count",
    "allocations": "allocation_count",
    "data read": "data_read_mb",
    "optimal throughput ratio": "optimal_throughput_ratio",
    "f1 improvement": "f1_improvement",
    "aff-f1 improvement": "aff_f1_improvement",
    "auc improvement": "auc_improvement",
    "bleu improvement": "bleu_improvement",
    "rouge-l improvement": "rouge_l_improvement",
    "weighted f1 decline": "weighted_f1_decline",
    "perplexity": "perplexity",
    "pcc": "pcc",
    "macro f1": "macro_f1",
    "macro precision": "macro_precision",
    "macro recall": "macro_recall",
    "weighted f1": "weighted_f1",
    "finalize time": "finalize_time_seconds",
    "rows/sec": "rows_per_second",
    "rows per second": "rows_per_second",
    "peak heapused": "peak_heap_used_mb",
    "file size": "artifact_size_mb",
    "fps": "frames_per_second",
    "speed fps": "frames_per_second",
    "frames per second": "frames_per_second",
    "samples/sec": "samples_per_second",
    "samples per second": "samples_per_second",
    "tflops": "tflops",
    "positions per second": "positions_per_second",
    "hitrate": "hit_rate",
    "hit rate": "hit_rate",
    "qps": "queries_per_second",
    "hits": "hit_count",
    "misses": "miss_count",
    "compression ratio": "compression_ratio",
    "search accuracy": "search_accuracy",
    "tok/s (med)": "tokens_per_second_medium",
    "tok/s (long)": "tokens_per_second_long",
    "math (50)": "math_accuracy",
    "samples": "sample_count",
    "no-target samples": "no_target_count",
    "n-acc": "negative_accuracy",
    "flops": "flop_count",
    "rx on dut, gb/s": "rx_dut_gbps",
    "rx on tester, gb/s": "rx_tester_gbps",
    "rx on dut, mpps": "rx_dut_mpps",
    "rx on tester, mpps": "rx_tester_mpps",
}

UNIT_INTERVAL_METRICS = {
    "accuracy",
    "precision",
    "recall",
    "f1",
    "hard_dice",
    "dice",
    "hard_iou",
    "iou",
    "miou",
    "boundary_f1",
    "map50_95",
    "map50",
    "map25",
    "map75",
    "ap",
    "ap50",
    "ap75",
    "ar",
    "pq",
    "top1_accuracy",
    "top5_accuracy",
    "auroc",
    "auprc",
    "brier_score",
    "mrr",
    "mndcg",
    "ndcg",
    "u_ndcg",
    "u_recall",
    "success_rate",
    "partial_rate",
    "fail_rate",
    "correctness",
    "answer_coverage",
    "specificity",
    "pro",
    "bleu",
    "bleu_1",
    "bleu_2",
    "bleu_3",
    "bleu_4",
    "rouge_l",
    "rouge_l_1",
    "rouge_l_2",
    "meteor",
    "cider",
    "text2mol",
    "mfu",
    "fragmentation_ratio",
    "optimal_throughput_ratio",
    "macro_f1",
    "macro_precision",
    "macro_recall",
    "weighted_f1",
    "hit_rate",
    "compression_ratio",
    "search_accuracy",
    "math_accuracy",
    "negative_accuracy",
}

NONNEGATIVE_METRICS = {
    "hausdorff95",
    "assd",
    "rmse",
    "mae",
    "mse",
    "log_loss",
    "runtime_seconds",
    "sign_time_seconds",
    "verify_time_seconds",
    "sync_time_without_cache_seconds",
    "sync_time_with_cache_seconds",
    "speedup",
    "mean_tool_calls",
    "mean_tokens",
    "mean_wall_time_seconds",
    "avg_latency_seconds",
    "p95_latency_seconds",
    "latency_score_seconds",
    "peak_rss_mb",
    "memory_mb",
    "throughput_ops_per_second",
    "feature_count",
    "test_count",
    "artifact_size_mb",
    "separability_delta",
    "tflops_per_second_gpu",
    "tokens_per_second_gpu",
    "requests_per_second",
    "latency_stdev_seconds",
    "max_latency_seconds",
    "min_latency_seconds",
    "p99_latency_seconds",
    "p90_latency_seconds",
    "p50_latency_seconds",
    "assertion_count",
    "allocation_count",
    "data_read_mb",
    "finalize_time_seconds",
    "rows_per_second",
    "peak_heap_used_mb",
    "frames_per_second",
    "samples_per_second",
    "tflops",
    "positions_per_second",
    "queries_per_second",
    "hit_count",
    "miss_count",
    "tokens_per_second_medium",
    "tokens_per_second_long",
    "sample_count",
    "no_target_count",
    "flop_count",
    "rx_dut_gbps",
    "rx_tester_gbps",
    "rx_dut_mpps",
    "rx_tester_mpps",
    "perplexity",
    "pcc",
}

_CANONICAL_METRICS = set(METRIC_ALIASES.values())


def canonical_metric(name: object) -> str:
    raw = str(name).strip().casefold()
    if raw in METRIC_ALIASES:
        return METRIC_ALIASES[raw]
    normalized = re.sub(r"[^\w²]+", "_", raw, flags=re.UNICODE).strip("_")
    return METRIC_ALIASES.get(normalized, normalized)


def metric_family(name: object) -> str | None:
    canonical = canonical_metric(name)
    if canonical in _CANONICAL_METRICS:
        return canonical
    readable = re.sub(r"[^\w²]+", " ", canonical.replace("_", " "), flags=re.UNICODE).strip()
    if re.search(r"\bmap\b", readable):
        if re.search(r"\b50\s+95\b", readable):
            return "map50_95"
        if re.search(r"\b75\b", readable):
            return "map75"
        if re.search(r"\b50\b", readable):
            return "map50"
    if re.search(r"\bmaph?\b", readable) and re.search(r"\bl[12]\b", readable):
        return "ap"
    for alias in sorted(METRIC_ALIASES, key=len, reverse=True):
        normalized_alias = re.sub(
            r"[^\w²]+", " ", alias.casefold().replace("_", " "), flags=re.UNICODE
        ).strip()
        if normalized_alias and re.search(rf"(?<!\w){re.escape(normalized_alias)}(?!\w)", readable):
            return METRIC_ALIASES[alias]
    return None


def is_unit_interval_metric(name: object) -> bool:
    return metric_family(name) in UNIT_INTERVAL_METRICS


def is_nonnegative_metric(name: object) -> bool:
    return metric_family(name) in NONNEGATIVE_METRICS


def scoped_metric_name(parts: list[object] | tuple[object, ...]) -> str | None:
    for index, part in enumerate(parts):
        if metric_family(part) is not None:
            return canonical_metric("_".join(str(value) for value in parts[index:]))
    return None
